packages:
  - "packages/flixlix-cards/*"
  - "packages/shared"
  - "packages/tooling/*"

catalogs:
  packages:
    "@babel/core": ^7.29.0
    "@babel/preset-env": ^7.29.3
    "@babel/preset-typescript": ^7.28.5
    "@mdi/js": ^7.4.47
    "@types/sortablejs": ^1.15.9
    "@rollup/plugin-babel": ^7.0.0
    "@rollup/plugin-commonjs": ^29.0.2
    "@rollup/plugin-json": ^6.1.0
    "@rollup/plugin-node-resolve": ^16.0.3
    "@rollup/plugin-terser": ^1.0.0
    "@rollup/plugin-typescript": ^12.3.0
    custom-card-helpers: ^1.9.0
    home-assistant-js-websocket: ^8.2.0
    lit: ^3.3.2
    lit-element: ^2.5.1
    lit-html: ^2.8.0
    memoize-one: ^6.0.0
    rollup: ^4.60.2
    rollup-plugin-minify-html-literals: ^1.2.6
    rollup-plugin-serve: ^1.1.1
    superstruct: ^1.0.4
    tslib: ^2.8.1

catalog:
  typescript: ^5.9.3
