name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.0.10
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Upload dist
        uses: actions/upload-artifact@v7.0.1
        with:
          name: power-flow-card-plus
          path: power-flow-card-plus.js